using System;
using System.Globalization;
using System.Linq;
using Avalonia;
using Avalonia.Media;

namespace Snowman.Core.Entities;

public class PolygonEntity : Entity
{
    private bool _isClosed;
    
    public bool CanBeClosed => Children.Count > 2;

    public PolygonEntity(Point point1, Point point2) : base(point1)
    {
        var firstSegment = new SegmentEntity(point1, point2, this);
        var controlPoint = firstSegment.Children[0];
        firstSegment.Children[1].IsVisible = false;
        controlPoint.PositionChanges += (_, _) => SetPositionWithoutRaisingEvent(controlPoint.Position);
        firstSegment.PositionChanges += (_, _) => SetPositionWithoutRaisingEvent(firstSegment.Children[0].Position);
        _children.Add(firstSegment);
        PositionChanges += OnPositionChanges;
        // var controlPoint = new PointEntity(point1, this);
        // controlPoint.PositionChanges += (_, _) => SetPositionWithoutRaisingEvent(controlPoint.Position);
        // _children.Add(controlPoint);
        // _children.Add(new PointEntity(point2, this) { IsVisible = false });
        // PositionChanges += OnPositionChanges;
    }

    public void AddPoint(Point point)
    {
        _children[^1].Children[1].IsVisible = true;
        var nextSegment = new SegmentEntity(_children[^1].Children[1] as PointEntity ?? throw new InvalidOperationException(), point, this);
        nextSegment.Children[1].IsVisible = false;
        _children.Add(nextSegment);
        RaiseEntityChanged();
        // _children[^1].IsVisible = true;
        // _children.Add(new PointEntity(point, this) { IsVisible = false });
        // RaiseEntityChanged();
    }

    public void ClosePolygon()
    {
        _children[^1]._children[1] = _children[0].Children[0];
        _children[^1].PositionChanges += (_, _) => SetPositionWithoutRaisingEvent(_children[^1].Children[1].Position);
        _isClosed = true;
        RaiseEntityChanged();
    }
    
    public override void Render(DrawingContext drawingContext)
    {
        if (!IsVisible) return;
        
        var points = GetRawPoints();
        var geometry = new StreamGeometry();
        
        using (var geometryContext = geometry.Open())
        {
            geometryContext.BeginFigure(points[0], true);

            for (var i = 1; i < points.Length; i++)
            {
                geometryContext.LineTo(points[i], false);
                drawingContext.DrawLine(GetPen(), points[i - 1], points[i]);
            }
            
            geometryContext.EndFigure(true);

            if (_isClosed)
            {
                drawingContext.DrawLine(GetPen(), points[^1], points[0]);
            }
        }
        
        drawingContext.DrawGeometry(GetBrush(), null, geometry);
        
        foreach (var child in Children)
        {
            child.Render(drawingContext);
        }
        
        if (Parent is null)
        {
            drawingContext.DrawText(new FormattedText(ToString(), CultureInfo.CurrentCulture, FlowDirection.LeftToRight, Typeface.Default, 10, GetBrush(1)), Position + new Vector(-7, -17));
        }
    }

    public override bool EvaluateHit(Point p)
    {
        if (!IsVisible) return false;
        
        var points = GetRawPoints();
        // lines below were copied from Google Gemini with no thought put into them
        var isInside = false;
        var n = points.Length;

        // We use two pointers: i is the current vertex, j is the previous one
        for (int i = 0, j = n - 1; i < n; j = i++)
        {
            // Check if the point is within the vertical bounds of the edge
            var isBetweenY = (points[i].Y > p.Y) != (points[j].Y > p.Y);

            if (!isBetweenY) continue;
            // Calculate the X-coordinate of the intersection of the edge 
            // with a horizontal line at the point's Y-coordinate.
            var intersectX = (points[j].X - points[i].X) * (p.Y - points[i].Y) / 
                (points[j].Y - points[i].Y) + points[i].X;

            // If the point is to the left of the intersection, toggle the state
            if (p.X < intersectX)
            {
                isInside = !isInside;
            }
        }

        return isInside;
    }

    public override bool EvaluateHit(Rect rect)
    {
        var polygon = GetRawPoints();
        // the rest of this method has been generated by Google Gemini
        // 1. Convert Rect to an array of points for uniform processing
        var rectPoints = new[]
        {
            rect.TopLeft,
            new Point(rect.Right, rect.Top),
            rect.BottomRight,
            new Point(rect.Left, rect.Bottom)
        };

        // 2. Collect all axes we need to check (the normals of the edges)
        var axes = GetAxes(polygon).Concat(GetAxes(rectPoints));

        foreach (var axis in axes)
        {
            // 3. Project both shapes onto the axis
            var (minA, maxA) = Project(polygon, axis);
            var (minB, maxB) = Project(rectPoints, axis);

            // 4. If there is a gap on ANY axis, they do not intersect
            if (maxA < minB || maxB < minA)
            {
                return false;
            }
        }

        return true;
    }

    public Point[] GetRawPoints()
    {
        return _children.SelectMany(child => child.Children).Select(x => x.Position).ToArray();
    }

    private void OnPositionChanges(Entity sender, Point oldPosition)
    {
        var vec = Position - oldPosition;
        
        foreach (var childSegment in Children)
        {
            childSegment.Children[0].SetPositionWithoutRaisingEvent(childSegment.Children[0].Position + vec);
        }
    }
    
    // this helper method has been generated by Google Gemini to aid with polygon x rectangle intersection evaluation
    private static Point[] GetAxes(Point[] points)
    {
        var axes = new Point[points.Length];
        
        for (var i = 0; i < points.Length; i++)
        {
            var p1 = points[i];
            var p2 = points[i + 1 == points.Length ? 0 : i + 1];
            
            // Get the edge vector
            var edge = p2 - p1;
            // Get the normal (perpendicular) vector: (-y, x)
            axes[i] = new Point(-edge.Y, edge.X);
            
            // Normalize the vector for accurate projection
            var length = Math.Sqrt(axes[i].X * axes[i].X + axes[i].Y * axes[i].Y);
            
            if (length > 0) axes[i] /= length;
        }
        return axes;
    }

    // this helper method has been generated by Google Gemini to aid with polygon x rectangle intersection evaluation
    private static (double min, double max) Project(Point[] points, Point axis)
    {
        var min = double.PositiveInfinity;
        var max = double.NegativeInfinity;

        foreach (var p in points)
        {
            // Dot product
            var dot = p.Y * axis.Y + p.X * axis.X;
            
            if (dot < min) min = dot;
            if (dot > max) max = dot;
        }

        return (min, max);
    }
}
