using System;
using System.Globalization;
using Avalonia;
using Avalonia.Media;
using Snowman.Utilities;

namespace Snowman.Core.Entities;

public class SegmentEntity : Entity
{
    public SegmentEntity(Point point1, Point point2, Entity? parent = null) : base(point1, parent)
    {
        var controlPoint = new PointEntity(point1, this);
        controlPoint.PositionChanges += (_, _) => SetPositionWithoutRaisingEvent(controlPoint.Position);
        ChildrenInternal.Add(controlPoint);
        ChildrenInternal.Add(new PointEntity(point2, this));
        
        PositionChanges += OnPositionChanges;
    }

    public SegmentEntity(PointEntity pointEntity, Point point, Entity? parent = null) : base(pointEntity.Position,
        parent)
    {
        pointEntity.PositionChanges += (_, _) => SetPositionWithoutRaisingEvent(pointEntity.Position);
        ChildrenInternal.Add(pointEntity);
        ChildrenInternal.Add(new PointEntity(point, this));
        
        PositionChanges += OnPositionChanges;
    }

    public override void Render(DrawingContext drawingContext)
    {
        if (!IsVisible) return;
        
        drawingContext.DrawLine(GetPen(), ChildrenInternal[0].Position, ChildrenInternal[1].Position);
        
        foreach (var child in Children) 
        {
            child.Render(drawingContext);
        }
        
        if (Parent is null)
        {
            drawingContext.DrawText(new FormattedText(ToString(), CultureInfo.CurrentCulture, FlowDirection.LeftToRight, Typeface.Default, 10, GetBrush(1)), Position + new Vector(-7, -17));
        }
    }

    public override bool EvaluateHit(Point cursorPosition)
    {
        var pointerDist = cursorPosition.DistanceTo(ChildrenInternal[0].Position) + cursorPosition.DistanceTo(ChildrenInternal[1].Position);
        var pointDist = ChildrenInternal[0].Position.DistanceTo(ChildrenInternal[1].Position);
        return IsVisible && 1 > pointerDist - pointDist;
    }

    public override bool EvaluateHit(Rect rect)
    {
        var p1 = ChildrenInternal[0].Position;
        var p2 = ChildrenInternal[1].Position;
        
        // the reset of this method has been generated by Google Gemini
        // 1. Quick Test: If either endpoint is inside the rectangle, they intersect
        if (rect.Contains(p1) || rect.Contains(p2)) return true;

        // 2. Check intersection against each of the four edges of the rectangle
        var topLeft = rect.TopLeft;
        var topRight = new Point(rect.Right, rect.Top);
        var bottomLeft = new Point(rect.Left, rect.Bottom);
        var bottomRight = rect.BottomRight;

        return LineSegmentsIntersect(p1, p2, topLeft, topRight) ||   // Top edge
               LineSegmentsIntersect(p1, p2, topRight, bottomRight) || // Right edge
               LineSegmentsIntersect(p1, p2, bottomRight, bottomLeft) || // Bottom edge
               LineSegmentsIntersect(p1, p2, bottomLeft, topLeft);     // Left edge
    }

    private void OnPositionChanges(Entity sender, Point oldPosition)
    {
        var vec = Position - oldPosition;

        foreach (var child in Children)
        {
            child.SetPositionWithoutRaisingEvent(child.Position + vec);
        }
    }
    
    // helper method generated by Google Gemini
    private static bool LineSegmentsIntersect(Point a, Point b, Point c, Point d)
    {
        // Using the cross product (orientation) method
        var denominator = (b.X - a.X) * (d.Y - c.Y) - (b.Y - a.Y) * (d.X - c.X);
        
        // Lines are parallel
        if (Math.Abs(denominator) < 1e-10) return false;

        var numerator1 = (a.Y - c.Y) * (d.X - c.X) - (a.X - c.X) * (d.Y - c.Y);
        var numerator2 = (a.Y - c.Y) * (b.X - a.X) - (a.X - c.X) * (b.Y - a.Y);

        var t = numerator1 / denominator;
        var u = numerator2 / denominator;

        // If t and u are between 0 and 1, the segments intersect
        return t is >= 0 and <= 1 && u is >= 0 and <= 1;
    }
}
